import pandas as pd,numpy as np
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
PROJECT_PATH='/content/drive/MyDrive/Colab Notebooks/market_ml_project'; INDEX_NAME='BANKNIFTY'; SPLIT_DATE='2024-01-01'; FILES={'NIFTY':'nifty_daily_features.csv','BANKNIFTY':'banknifty_daily_features.csv','SENSEX':'sensex_daily_features.csv'}
df=pd.read_csv(f'{PROJECT_PATH}/{FILES[INDEX_NAME]}',parse_dates=['Date']).set_index('Date').sort_index(); df['future_close_5d']=df.Close.shift(-5); df['future_return_5d']=(df.future_close_5d-df.Close)/df.Close; df['label']=(df.future_close_5d>df.Close).astype(int); df['price_range']=(df.High-df.Low)/df.Close; df['close_position']=(df.Close-df.Low)/(df.High-df.Low+1e-9); df['gap']=df.Open/df.Close.shift(1)-1; df['ema20_slope']=df.ema_20.pct_change(2); df['ema50_slope']=df.ema_50.pct_change(5); df['ema20_50_cross']=(df.ema_20>df.ema_50).astype(int); df['ema50_100_cross']=(df.ema_50>df.ema_100).astype(int); df['rsi_overbought']=(df.rsi_14>70).astype(int); df['rsi_oversold']=(df.rsi_14<30).astype(int); df['macd_cross']=(df.macd>df.macd_signal).astype(int); df['trend_strong']=(df.adx>25).astype(int); df['di_cross']=(df.plus_di>df.minus_di).astype(int); df['return_1d']=df.Close.pct_change(); df['return_3d']=df.Close.pct_change(3); df['return_5d']=df.Close.pct_change(5); df['return_10d']=df.Close.pct_change(10); df['volatility_10d']=df.return_1d.rolling(10).std(); df['volatility_20d']=df.return_1d.rolling(20).std(); df['vol_ratio']=df.volatility_10d/(df.volatility_20d+1e-9); df['obv_momentum']=df.obv.pct_change(5); df.dropna(inplace=True)
DROP=['label','future_close_5d','future_return_5d','Open','High','Low','Close','Volume']; X=df[[c for c in df.columns if c not in DROP]].replace([np.inf,-np.inf],np.nan); y=df.label; Xtr,Xte=X[X.index<SPLIT_DATE],X[X.index>=SPLIT_DATE]; ytr,yte=y[y.index<SPLIT_DATE],y[y.index>=SPLIT_DATE]
model=Pipeline([('imputer',SimpleImputer(strategy='median')),('scaler',StandardScaler()),('model',SVC(C=1.0,kernel='rbf',probability=True,class_weight='balanced',random_state=42))]); model.fit(Xtr,ytr); pred=model.predict(Xte); print(f'{INDEX_NAME} | 5-Day Technical SVM | Accuracy: {accuracy_score(yte,pred):.4f}'); print(classification_report(yte,pred,target_names=['Bearish','Bullish'])); print(confusion_matrix(yte,pred))
